[[resolver]]
enable = false
address = "http://127.0.0.1:8888"

[[group]]
template = "https://*.vecno.stream"
nodes = ["eric","maxim","sean","troy"]

[[group]]
template = "https://*.vecno.red"
nodes = ["john", "mike", "paul", "alex"]

[[group]]
template = "https://*.vecno.green"
nodes = ["jake", "mark", "adam", "liam"]

[[group]]
template = "https://*.vecno.blue"
nodes = ["noah", "ryan", "jack", "luke"]

# [[group]]
# enable = true
# template = "https://*.vecno-ng.org"
# nodes = ["cole", "ivan", "oscar", "zane"]

# [[group]]
# enable = true
# template = "https://*.vecno-ng.io"
# nodes = ["gary", "hugo", "finn", "evan"]

# [[group]]
# enable = true
# template = "https://*.vecno-ng.net"
# nodes = ["neil", "dave", "kyle", "toby"]

# ---

# [[group]]
# enable = false
# template = "https://*."
# nodes = ["rudy", "todd", "clay", "walt"]
